# Generated by Django 4.2.16 on 2025-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_suspended_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(choices=[('client', 'Client'), ('rental', 'Rental (Single Person)'), ('company', 'Company')], default='', max_length=10),
        ),
    ]
