# Generated by Django 4.2.16 on 2025-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
