# Generated by Django 4.2.16 on 2025-05-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('client', 'Client'), ('rental', 'Rental (Single Person)'), ('company', 'Company'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
